version: '3.4'
services:
  appium:
    build: ./appium
    container_name: appium
    privileged: true
    ports:
      - "4723:4723"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
